### ISSUE TITLE
BaseRTMPClientHandler.java Null pointer exception

### ISSUE THREAD

**Issue by NomiJ** [Red5/red5-client#24]
While trying to run red-client/ClientTest.java with twitch server, there is a null pointer exception 

ClientTest.Java
=============
private String server = "live.twitch.tv";
private int port = 1935;
private String application = "app/Twitch_Key_Here";

Log
===
https://gist.github.com/NomiJ/f5a5f836192e7afc029a

Android23 Support
===============
Moreover, I wonder if there would be patch for this to work with latest android,

>> https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

Thanks

**Comment by mondain** [comment]
Your log shows a lot of calls to demoService.getListOfAvailableFLVs which is a method available in the oflaDemo server application demo; I'm not sure that its relevant to the "twitch" server issue you're reporting.
