### ISSUE TITLE
restreaming to wowza

### ISSUE THREAD

**Issue by LazyProphet** [Red5/red5-client#32]
Hi, 
I'm trying to publish a video stream from red5 to wowza.

I had Problems setting up the Proxy with `org.red5.proxy.StreamingProxy`.
After some debugging I found out that the stream id comes as Double.
Changing `private int streamId;` to `private Number streamId;` [(here)](https://github.com/Red5/red5-client/blob/master/src/main/java/org/red5/proxy/StreamingProxy.java#L74) solved my problem.  Don't know if any other streaming servers are affected.

Kind regards

**Comment by mondain** [comment]
That streamId seems to have slipped through the cracks, most everything else in Red5 for stream ids is Number type. Thanks for the PR.
