### ISSUE TITLE
StreamingProxy.isRunning() causes null pointer exception

### ISSUE THREAD

**Issue by jdc18** [Red5/red5-client#37]
I dont know if this is a bug, or it is a design thing, so here is this issue I am facing.
I am declaring a StreamingProxy object and initializing.  I am checking if the proxy is running or not depending at first it is something like this

```
		if(streamer.isRunning()){
			log.info("Is Running");
		}else{
			log.info("No esta corriendo");
		}
```
I am getting 
"Caused by: java.lang.NullPointerException: null
at org.red5.proxy.StreamingProxy.isRunning(StreamingProxy.java:241)",
 and it makes sense because the state is never set even if it is initialized  because there is no constructor or anything.
Shouldnt it starts as stopped?

**Comment by mondain** [comment]
I added UNINITIALIZED state and this should be resolved in next push.
