### ISSUE TITLE
Memory leak in red5-client

### ISSUE THREAD

**Issue by MoathAlshorman** [Red5/red5-client#42]
I've faced this issue when I was using red5-client v1.0.5-RELEASE so I've upgraded the red5-client to v1.0.9-RELEASE but still there is a memory leak.

Details:

Below is a description for the memory leak reason in red5-client v1.0.9-RELEASE, although there is a memory leak in v1.0.5-RELEASE but with different causes but will not talk about here.

connMap Map in org.red5.client.net.rtmp.RTMPConnManager causes this leakage. Connection will be put in the map when connection is created and removed when connection is closed. However, removeConnection method that handles removing connection from connMap never be reached.

```
/** {@inheritDoc} */
    @Override
    public RTMPConnection removeConnection(String sessionId) {
        log.debug("Removing connection with session id: {}", sessionId);
        if (log.isTraceEnabled()) {
            log.trace("Connections ({}) at pre-remove: {}", connMap.size(), connMap.values());
        }
        // remove from map
        RTMPConnection conn = connMap.remove(sessionId);
        if (conn != null) {
            log.trace("Connections: {}", conns.decrementAndGet());
            Red5.setConnectionLocal(null);
        }
        return conn;
    }
```
Because there is a condition in connectionClosed method from org.red5.server.net.rtmp.BaseRTMPHandler to invoke above removeConnection(String sessionId) and this condition will never be true.

```
/** {@inheritDoc} */
    public void connectionClosed(RTMPConnection conn) {
        log.debug("connectionClosed: {}", conn.getSessionId());
        if (conn.getStateCode() != RTMP.STATE_DISCONNECTED) {
            // inform any callbacks for pending calls that the connection is closed
            conn.sendPendingServiceCallsCloseError();
            // close the connection
            if (conn.getStateCode() != RTMP.STATE_DISCONNECTING) {
                conn.close();
            }
            // set as disconnected
            conn.setStateCode(RTMP.STATE_DISCONNECTED);
        }
        IoSession session = conn.getIoSession();
        // This is the condition I'm talking about>>
        if (session != null && session.containsAttribute(RTMPConnection.RTMP_CONN_MANAGER)) {
            // Unreachable code>>
            @SuppressWarnings("unchecked")
            IConnectionManager<RTMPConnection> connManager = (IConnectionManager<RTMPConnection>) ((WeakReference<?>) session.getAttribute(RTMPConnection.RTMP_CONN_MANAGER)).get();
            if (connManager != null) {
                connManager.removeConnection(conn.getSessionId());
            } else {
                log.debug("Connection manager was not found in the session");
            }
        }
        log.trace("connectionClosed: {}", conn);
    }
```
This session.getAttribute(RTMPConnection.RTMP_CONN_MANAGER) asks for an attribute with name rtmp.connection.manager to get the connectionManager instance but it doesn't exist because no one set this attribute!

I've looked at org.red5.server.net.rtmp.RTMPMinaIoHandler class, it's very similar to the one in the client but it sets the rtmp.connection.manager attribute with connectionManager instance when sessionOpened as below:

```
/** {@inheritDoc} */
    @Override
    public void sessionOpened(IoSession session) throws Exception {
        String sessionId = (String) session.getAttribute(RTMPConnection.RTMP_SESSION_ID);
        log.debug("Session opened: {} id: {}", session.getId(), sessionId);
        RTMPConnManager connManager = (RTMPConnManager) RTMPConnManager.getInstance();
        session.setAttribute(RTMPConnection.RTMP_CONN_MANAGER, new WeakReference<IConnectionManager<RTMPConnection>>(connManager));
        RTMPMinaConnection conn = (RTMPMinaConnection) connManager.getConnectionBySessionId(sessionId);
        handler.connectionOpened(conn);
    }
```
But org.red5.client.net.rtmp.RTMPMinaIoHandler doesn't and that what causes the issue:

```
/** {@inheritDoc} */
    @Override
    public void sessionOpened(IoSession session) throws Exception {
        log.debug("Session opened");
        super.sessionOpened(session);
        // get the handshake from the session
        RTMPHandshake handshake = (RTMPHandshake) session.getAttribute(RTMPConnection.RTMP_HANDSHAKE);
        // create and send C0+C1
        IoBuffer clientRequest1 = ((OutboundHandshake) handshake).generateClientRequest1();
        session.write(clientRequest1);
    }
```
Could you advice me if my conclusion is right and this is a really memory leak or there is something I misunderstood?
I've asked a question on stackOverflow with the same contents, you can find it [here](https://stackoverflow.com/questions/49776482/memory-leak-in-red5-client)

**Comment by MoathAlshorman** [comment]
Could you advice me if you have a time @mondain 
Thanks in advance.

**Comment by mondain** [comment]
The server and client RTMPMinaIoHandlers are similar but due to their roles are different; both client and server have different handshakes to start. I don't believe the client uses a connection manager unless its used on the server, but I may just be foggy on the current process. Use `containsAttribute` if you're having issues with an attribute lookup.

**Comment by MoathAlshorman** [comment]
I've fixed the issue by adding the following lines to org.red5.client.net.rtmp.RTMPMinaIoHandler.sessionOpened(IoSession session) method as you did with org.red5.server.net.rtmp.RTMPMinaIoHandler.
@mondain Is this has side effects? because I tested it; memory leak was solved and everything worked well.
```
RTMPConnManager connManager = (RTMPConnManager) RTMPConnManager.getInstance();
        session.setAttribute(RTMPConnection.RTMP_CONN_MANAGER, new WeakReference<IConnectionManager<RTMPConnection>>(connManager));
```

**Comment by mondain** [comment]
A fix for this using the WeakReference in the session will be in the next commit.

**Comment by MoathAlshorman** [comment]
Thank you!
