### ISSUE TITLE
Red5 Client - Rtmp stream to FLV

### ISSUE THREAD

**Issue by GoelBiju** [Red5/red5-client#43]
Hi @mondain ,

I had accomplished to run the ClientTest java file with a custom server host, port and stream name set in the PropertiesReader and the client was able to connect successfully.

I was wondering how I would be able to save the audio/video and aggregate messages into an FLV file from the stream. I am aware that Red5-io has the functionality to read and write FLV files however I do not know how to make ClientTest output to an FLV file.

Thank you.

**Comment by mondain** [comment]
The server utilizes red5-io for writing an FLV; there is no current mechanism to go straight from red5-client to FLV file; you'd have to implement parts of the FLVWriter and pass it Tag instances.

**Comment by GoelBiju** [comment]
@mondain , thank you for your response.
